
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
  labels:
    app: quiz-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: quiz-app
    tier: frontend